"""Phase 4 experiments: baselines + GNN on the MASKED graph over leak-free splits, a leakage ablation, and a herb-level gold check.
Resumable at fold granularity: results are appended to data/processed/phase4/results.csv as each fold finishes."""
import argparse
import time
from pathlib import Path

import numpy as np
import pandas as pd

from ayurveda_kg import baselines, evaluate, features, masking
from ayurveda_kg.kg import load_tables

OUT = Path("data/processed/phase4")
MODEL_SEEDS = {"prior": [0], "rf": [0], "rf_leaky": [0], "mf": [0], "gnn": [0, 1, 2], "mlp": [0, 1, 2]}   # mlp = gnn with 0 graph layers
METRICS = ["auroc", "auprc", "p_at_100"]
KEY = ["split", "model", "seed", "fold"]


def summarize(res: pd.DataFrame) -> pd.DataFrame:
    """Average seeds within each fold first, then mean/std/min/max across folds (folds are very uneven, so keep min/max)."""
    per_fold = res.groupby(["split", "model", "fold"], as_index=False)[METRICS + ["n_test", "n_pos"]].mean()
    g = per_fold.groupby(["split", "model"])
    out = g.agg(auroc_mean=("auroc", "mean"), auroc_std=("auroc", "std"), auroc_min=("auroc", "min"), auroc_max=("auroc", "max"),
                auprc_mean=("auprc", "mean"), auprc_std=("auprc", "std"), p_at_100_mean=("p_at_100", "mean"),
                n_folds=("fold", "nunique")).reset_index()
    return out


def gold_model_scores(preds: pd.DataFrame, contains: pd.DataFrame, gold: pd.DataFrame) -> pd.DataFrame:
    """Herb-drug score = mean predicted probability over the herb's held-out compounds; percentile among all scored herb-drug pairs."""
    m = preds.merge(contains.rename(columns={"src": "herb", "dst": "compound"})[["herb", "compound"]], on="compound")
    s = m.groupby(["herb", "drug"], as_index=False)["p"].mean().rename(columns={"p": "model_score"})
    s["model_percentile"] = s["model_score"].rank(pct=True)
    s["herb"], s["drug"] = s["herb"].str.removeprefix("herb:"), s["drug"].str.removeprefix("drug:")
    return gold.merge(s, on=["herb", "drug"], how="left")


def make_phase4_report(res: pd.DataFrame, gold: pd.DataFrame, grouped: pd.DataFrame = None) -> str:
    """Markdown report. Every comparative statement is computed from `res`, never hand-written."""
    s = summarize(res)
    L = ["# Phase 4 results", "", "Generated by `python -m ayurveda_kg.phase4_report`. Do not edit by hand.", "",
         "Task: predict the Phase 3 silver label for (compound, drug) pairs from the **masked** graph (no CYP label-source edges) plus compound "
         "chemistry. Folds are leak-free (see `docs/labels_report.md`). `random_pair` is an inflated reference only; `rf_leaky` is the leakage "
         "ablation (the same RF given the unmasked CYP features).", "",
         "## Summary (mean over folds; GNN seeds averaged within each fold first)", "",
         "| split | model | AUROC mean | AUROC std | AUROC min-max | AUPRC mean | P@100 mean | folds |", "|---|---|---|---|---|---|---|---|"]
    order = {"prior": 0, "mf": 1, "rf": 2, "mlp": 3, "gnn": 4, "rf_leaky": 5}
    for r in s.sort_values(["split", "model"], key=lambda c: c.map(order) if c.name == "model" else c).itertuples():
        L.append(f"| {r.split} | {r.model} | {r.auroc_mean:.3f} | {r.auroc_std:.3f} | {r.auroc_min:.3f}-{r.auroc_max:.3f} | "
                 f"{r.auprc_mean:.3f} | {r.p_at_100_mean:.3f} | {r.n_folds} |")
    cold = ["cold_compound", "cold_herb", "cold_drug"]
    m = s.set_index(["split", "model"])["auroc_mean"]
    have = [c for c in cold if (c, "gnn") in m.index and (c, "rf") in m.index]
    wins = [c for c in have if m[(c, "gnn")] > m[(c, "rf")]]
    L += ["", "## Reading the comparison (computed from the table)", ""]
    if have:
        L.append(f"- GNN has the higher mean AUROC than the Random Forest on {len(wins)} of {len(have)} cold splits.")
        L += [f"- {c}: {'gnn' if m[(c, 'gnn')] > m[(c, 'rf')] else 'rf'} ahead by {abs(m[(c, 'gnn')] - m[(c, 'rf')]):.3f} AUROC "
              f"(gnn {m[(c, 'gnn')]:.3f}, rf {m[(c, 'rf')]:.3f})." for c in have]
        L += [f"- cold_drug: {'gnn' if m[('cold_drug', 'gnn')] > m[('cold_drug', 'rf')] else 'rf'} is the better model there."] if "cold_drug" in have else []
        L.append("- Differences of about one fold-std or less should not be read as a real advantage.")
    ab = [(c, m[(c, "gnn")] - m[(c, "mlp")]) for c in cold if (c, "gnn") in m.index and (c, "mlp") in m.index]
    if ab:
        L += ["", "## Does graph structure help? (GNN vs the same network with no message passing, `mlp`)", ""]
        L += [f"- {c}: gnn minus mlp = {d:+.3f} AUROC." for c, d in ab]
        L.append("- A difference near zero means the graph adds nothing beyond the node features (compound chemistry, targets, drug class, DDI profile).")
    if grouped is not None and len(grouped):
        L += ["", "## Where the skill comes from: within-drug and within-compound AUROC", "",
              "Pooled AUROC can reward a model that only knows each drug's base rate or only whether a compound inhibits any CYP. "
              "Within-drug AUROC ranks compounds for one drug (compound-side skill); within-compound AUROC ranks drugs for one compound "
              "(drug-side skill). Groups with a single class are skipped.", "",
              "| split | model | within-drug AUROC | drugs | within-compound AUROC | compounds |", "|---|---|---|---|---|---|"]
        for r in grouped.sort_values(["split", "model"], key=lambda c: c.map(order) if c.name == "model" else c).itertuples():
            L.append(f"| {r.split} | {r.model} | {r.within_drug_auroc:.3f} | {r.n_drugs} | {r.within_compound_auroc:.3f} | {r.n_compounds} |")
        cd = grouped[(grouped["split"] == "cold_drug") & grouped["model"].isin(["rf", "mlp", "gnn"])]
        if len(cd):
            L += ["", "On the cold-drug split (computed):", ""]
            for r in cd.itertuples():
                pooled = f"pooled AUROC {m[('cold_drug', r.model)]:.3f}, " if ("cold_drug", r.model) in m.index else ""
                L.append(f"- {r.model}: {pooled}compound-side (within-drug) AUROC {r.within_drug_auroc:.3f}, "
                         f"drug-side (within-compound) AUROC {r.within_compound_auroc:.3f}.")
            L.append("- The pooled cold-drug score is therefore mostly compound-side skill; generalisation to unseen drugs is the within-compound column "
                     "(0.5 = chance).")
    lk = [(c, m[(c, "rf_leaky")] - m[(c, "rf")]) for c in cold if (c, "rf_leaky") in m.index and (c, "rf") in m.index]
    L += ["", "## Leakage ablation", ""]
    L += [f"- {c}: RF with unmasked CYP features reaches mean AUROC {m[(c, 'rf_leaky')]:.3f} vs {m[(c, 'rf')]:.3f} with the masked graph "
          f"({d:+.3f}); the masked graph removes this inflation." for c, d in lk]
    f = res[res["model"].isin(["rf", "gnn"]) & (res["split"] == "cold_herb")].groupby(["model", "fold"])["auroc"].mean().unstack(0)
    if len(f):
        L += ["", "## Per-fold AUROC, cold-herb split (folds differ a lot, so read the spread, not only the mean)", "",
              "| fold | " + " | ".join(f.columns) + " |", "|---|" + "---|" * len(f.columns)]
        L += [f"| {i} | " + " | ".join(f"{v:.3f}" for v in row) + " |" for i, row in f.iterrows()]
    L += ["", "## Herb-level check against the literature gold set", ""]
    if len(gold):
        L += ["Model score = mean predicted probability over the herb's held-out compounds (cold-herb out-of-fold); percentile among all scored "
              "herb-drug pairs. Silver columns repeat the Phase 3 mechanistic score for comparison.", "",
              "| Herb | Drug | Gold | Mechanism | Model | Model score | Model pct | Silver score | Silver pct |", "|---|---|---|---|---|---|---|---|---|"]
        for r in gold.itertuples():
            ms = "n/a" if pd.isna(r.model_score) else f"{r.model_score:.2f}"
            mp = "n/a" if pd.isna(r.model_percentile) else f"{r.model_percentile:.2f}"
            L.append(f"| {r.herb} | {r.drug} | {r.label} | {r.mechanism} | {r.model} | {ms} | {mp} | {r.frac_pos:.2f} | {r.percentile:.2f} |")
        for mdl in gold["model"].dropna().unique():
            gm = gold[gold["model"] == mdl]
            neg, pk = gm[gm["label"] == 0]["model_percentile"].dropna(), gm[(gm["label"] == 1) & (gm["mechanism"] == "PK")]["model_percentile"].dropna()
            if len(neg) and len(pk):
                L += ["", f"- {mdl}: gold negatives at percentiles {', '.join(f'{v:.2f}' for v in neg)}; PK positives {pk.min():.2f}-{pk.max():.2f} "
                          f"(median {pk.median():.2f}); {int((neg > pk.max()).sum())} of {len(neg)} negatives rank above every PK positive."]
        L += ["", "The models learn the *silver* labels, which are a mechanistic hypothesis (predicted CYP inhibition meets known substrate), "
              "not clinical truth. They inherit the silver false alarms (ginger-warfarin, garlic-warfarin) and cannot predict pharmacodynamic "
              "pairs. The gold set is 12 pairs with 2 negatives and is pending expert review: a qualitative case study, not a statistical test."]
    return "\n".join(L) + "\n"


def load_inputs(nbits=1024):
    nodes, edges = load_tables("data/processed/kg")
    labels = pd.read_parquet("data/processed/labels/silver.parquet")
    masked = masking.mask_label_edges(edges)
    masking.assert_no_label_leak(masked)                                  # fail loudly before any model sees the graph
    fe = features.build_features(nodes, masked, nbits=nbits)
    lc, ld, _ = features.leaky_label_features(nodes, edges)               # UNMASKED: used only by the rf_leaky ablation
    return nodes, edges, masked, labels, fe, (lc, ld)


def make_model(name, seed, fe, masked, leaky):
    if name == "prior":
        return baselines.prior_fit_predict
    if name == "rf":
        return baselines.rf_fit_predict(fe, seed=seed)
    if name == "rf_leaky":
        return baselines.rf_fit_predict(fe, seed=seed, extra_compound=leaky[0], extra_drug=leaky[1])
    if name == "mf":
        return baselines.mf_fit_predict(seed=seed)
    if name in ("gnn", "mlp"):
        from ayurveda_kg.gnn import gnn_fit_predict
        return gnn_fit_predict(fe, masked, seed=seed, layers=2 if name == "gnn" else 0)
    raise ValueError(name)


def run(models=None, splits=("cold_compound", "cold_herb", "cold_drug", "random_pair"), k=5, fold_seed=0):
    nodes, edges, masked, labels, fe, leaky = load_inputs()
    OUT.mkdir(parents=True, exist_ok=True)
    res_path, pred_dir = OUT / "results.csv", OUT / "preds"
    pred_dir.mkdir(exist_ok=True)
    done = pd.read_csv(res_path) if res_path.exists() else pd.DataFrame(columns=KEY)
    done_keys = set(map(tuple, done[KEY].values))
    print(f"features: Xc{fe.Xc.shape} Xd{fe.Xd.shape} invalid SMILES: {fe.n_bad_smiles}", flush=True)
    for split in splits:
        folds = evaluate.make_folds(split, labels, edges["contains"], k, fold_seed)
        for name in (models or MODEL_SEEDS):
            if name == "mf" and split != "random_pair":
                continue                                                  # MF cannot score unseen compounds/drugs: reference only
            for seed in MODEL_SEEDS[name]:
                fp = make_model(name, seed, fe, masked, leaky)
                for i, f in enumerate(folds):
                    if (split, name, seed, i) in done_keys:
                        continue
                    t0 = time.time()
                    p = np.asarray(fp(f["train_pairs"], f["test_pairs"], f))
                    assert len(p) == len(f["test_pairs"])
                    row = {"split": split, "model": name, "seed": seed, "fold": i, "n_train": len(f["train_pairs"]),
                           **evaluate.metrics(f["test_pairs"]["label"].values, p), "seconds": round(time.time() - t0, 1)}
                    pd.DataFrame([row]).to_csv(res_path, mode="a", header=not res_path.exists(), index=False)
                    te = f["test_pairs"][["compound", "drug", "label"]].assign(p=p, fold=i)
                    te.to_parquet(pred_dir / f"{split}_{name}_s{seed}_f{i}.parquet", index=False)
                    print(f"{split:14s} {name:9s} seed={seed} fold={i} auroc={row['auroc']:.3f} auprc={row['auprc']:.3f} "
                          f"({row['seconds']}s)", flush=True)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--models", default=None, help="comma list, default all")
    ap.add_argument("--splits", default="cold_compound,cold_herb,cold_drug,random_pair")
    a = ap.parse_args()
    run(a.models.split(",") if a.models else None, tuple(a.splits.split(",")))
