"""Phase 6 runner: text graph -> retrieval evaluation (synthetic questions) -> KG-grounded answer evaluation -> examples -> docs/phase6_results.md.
Stages are resumable and cached under data/processed/rag (derived from public-domain texts and local IMPPAT-derived data: not committed)."""
import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from ayurveda_kg import curated
from ayurveda_kg.rag import evaluate as ev
from ayurveda_kg.rag.build_index import OUT, load_chunks
from ayurveda_kg.rag.extract import cooccurrence_edges, load_triple_rows, ollama_client
from ayurveda_kg.rag.generate import DISCLAIMER, answer, check_citations, ollama_text_client, overclaim_flags
from ayurveda_kg.rag.index import DenseIndex, sentence_embedder
from ayurveda_kg.rag.kgfacts import KGFacts
from ayurveda_kg.rag.lexicon import load_lexicon
from ayurveda_kg.rag.retrieve import HybridRetriever
from ayurveda_kg.rag.textgraph import TextGraph
from ayurveda_kg.scope import load_scope

CONFIGS = {"plain": dict(use_alias=False, use_graph=False, use_kg=False), "alias": dict(use_alias=True, use_graph=False, use_kg=False),
           "graph": dict(use_alias=False, use_graph=True, use_kg=False), "alias+graph": dict(use_alias=True, use_graph=True, use_kg=False),
           "full": dict(use_alias=True, use_graph=True, use_kg=True)}
ANSWER_SYSTEMS = ["no_retrieval", "plain", "alias+graph", "full", "full_kfirst"]    # full_kfirst: same retrieval, KG facts placed first in the prompt
EXAMPLE_QUESTIONS = ["What does the Charaka Samhita say about treating cough?", "Which remedies are used for skin disease in the Sushruta Samhita?",
                     "How is turmeric used in classical Ayurveda?", "Is black pepper safe to take with phenytoin?",
                     "What is said about ginger and digestion?", "Which drugs may interact with licorice according to the research risk scores?"]


def summarize_answers(df: pd.DataFrame) -> pd.DataFrame:
    g = df.groupby(["system", "qtype"])
    return g.agg(correctness=("correct", "mean"), citation_validity=("citation_validity", "mean"), support_rate=("support_rate", "mean"),
                 refusal_rate=("refused", "mean"), n=("correct", "size")).reset_index()


def phase6_facts(stats: dict, retr: pd.DataFrame, gap: pd.DataFrame, answers: pd.DataFrame, overread: pd.DataFrame) -> dict:
    """Flat, JSON-safe numbers from a Phase 6 run (config names lose '+': alias+graph -> aliasgraph). The paper drafts are rendered from these."""
    key = lambda c: c.replace("+", "")
    f = {"chunks": stats["n_chunks"], "herbs_found": stats["herbs_found"], "herbs_total": stats["herbs_total"], "co_edges": stats["cooccurrence_edges"],
         "triples_rows": stats["triples_rows"], "triples_accepted": stats["triples_accepted"], "triples_rejected": stats["triples_rejected"]}
    for tag, df in (("retr", retr), ("gap", gap)):
        if df is not None:
            for _, r in df.iterrows():
                f[f"{tag}_{key(r['config'])}_r5"], f[f"{tag}_{key(r['config'])}_r10"] = float(r["recall@5"]), float(r["recall@10"])
                f[f"{tag}_{key(r['config'])}_mrr"], f[f"{tag}_n"] = float(r["mrr"]), int(r["n"])
    for r in summarize_answers(answers).itertuples():
        f[f"kg_{r.system}_{r.qtype}"], f[f"refusal_{r.system}_{r.qtype}"], f[f"n_{r.qtype}"] = float(r.correctness), float(r.refusal_rate), int(r.n)
    if overread is not None and len(overread):
        for r in summarize_overread(overread).itertuples():
            f[f"over_{r.variant}_n"], f[f"over_{r.variant}_d"] = int(r.n_overclaim), int(r.n_cocite)
    return f


def summarize_overread(df: pd.DataFrame) -> pd.DataFrame:
    g = df.groupby("variant").agg(n_cocite=("n_cocite", "sum"), n_overclaim=("n_overclaim", "sum"), questions=("qid", "nunique")).reset_index()
    g["rate"] = g["n_overclaim"] / g["n_cocite"].where(g["n_cocite"] > 0)
    return g


def make_phase6_report(stats: dict, retr: pd.DataFrame, answers: pd.DataFrame, examples: list[dict], retr_gap: pd.DataFrame = None,
                       overread: pd.DataFrame = None) -> str:
    L = ["# Phase 6 results", "", "Generated by `python -m ayurveda_kg.phase6`. Do not edit by hand.", "",
         "**What this is.** A GraphRAG assistant over two public-domain classical translations (Kaviratna *Charaka-Samhita*, Bhishagratna *Sushruta Samhita*) "
         "that retrieves passages, text-graph facts and project knowledge-graph facts (herb-drug research risk scores), answers with checkable citations using a "
         "local model (`qwen3:8b`), and always appends a research-use disclaimer. AyurParam is not used yet (deferred).", "",
         "## Corpus and graph", "",
         f"- {stats['n_chunks']} passages ({', '.join(f'{k}: {v}' for k, v in stats['per_text'].items())}).",
         f"- The alias lexicon finds {stats['herbs_found']} of {stats['herbs_total']} scoped herbs in the texts.",
         f"- Text graph: {stats['cooccurrence_edges']} co-occurrence edges (min 2 passages); LLM triple extraction over {stats['triples_rows']} herb+condition passages "
         f"accepted {stats['triples_accepted']} grounded triples and rejected {stats['triples_rejected']} ({stats['triples_errors']} model errors). "
         f"Relations: {', '.join(f'{k} {v}' for k, v in stats['relations'].items())}.",
         "- A triple is accepted only if its subject and object literally appear in the passage and resolve to lexicon entities. This removes hallucinated entities; "
         "the **precision of accepted triples is unverified until an expert checks a sample**.", "",
         "## Retrieval (synthetic questions)", "",
         "Questions were written by the local LLM from sampled passages (gold = the source passage). They are lexically easier than real questions, "
         "so absolute numbers are optimistic; the comparison between configurations is what matters.", "",
         "| config | recall@5 | recall@10 | MRR | questions |", "|---|---|---|---|---|"]
    L += [f"| {r.config} | {r._2:.3f} | {r._3:.3f} | {r.mrr:.3f} | {r.n} |" for r in retr.rename(columns={"recall@5": "_2", "recall@10": "_3"}).itertuples()]
    if retr_gap is not None and len(retr_gap):
        L += ["", "## Vocabulary-gap questions", "",
              "The synthetic questions above rarely name a herb in English, so they cannot test alias expansion. These questions are built from the extracted triples: "
              "they name the herb by its English common name (for example 'turmeric') while every supporting passage uses a Sanskrit name (for example 'Haridra') "
              "and neither the English nor the Latin name. Gold = the passages that support the triple.", "",
              "| config | recall@5 | recall@10 | MRR | questions |", "|---|---|---|---|---|"]
        L += [f"| {r.config} | {r._2:.3f} | {r._3:.3f} | {r.mrr:.3f} | {r.n} |" for r in retr_gap.rename(columns={"recall@5": "_2", "recall@10": "_3"}).itertuples()]
        g = retr_gap.set_index("config")
        if {"plain", "alias"} <= set(g.index):
            L += ["", f"Computed: alias expansion moves recall@5 from {g.loc['plain', 'recall@5']:.3f} to {g.loc['alias', 'recall@5']:.3f} on these questions."]
    s = summarize_answers(answers)
    L += ["", "## KG-grounded multi-hop questions", "",
          "Questions are generated from the knowledge graph (top-3 highest-risk drugs for a herb; the risk score of a herb-drug pair) and scored programmatically. "
          "Systems that can see KG facts have an advantage **by construction**: this shows what the graph adds, not general answer quality.", "",
          "| system | question type | correctness | citation validity | support rate | refusal rate | n |", "|---|---|---|---|---|---|---|"]
    order = {s_: i for i, s_ in enumerate(ANSWER_SYSTEMS)}
    for r in s.sort_values(["qtype", "system"], key=lambda c: c.map(order) if c.name == "system" else c).itertuples():
        cv = "n/a" if pd.isna(r.citation_validity) else f"{r.citation_validity:.3f}"
        sr = "n/a" if pd.isna(r.support_rate) else f"{r.support_rate:.3f}"
        L.append(f"| {r.system} | {r.qtype} | {r.correctness:.3f} | {cv} | {sr} | {r.refusal_rate:.3f} | {r.n} |")
    if "n_cocite" in answers.columns:
        fa = answers[answers["system"] == "full"]
        n_co, n_ov = int(fa["n_cocite"].sum()), int(fa["n_overclaim"].sum())
        if n_co:
            L += ["", f"Over-reading check (full system): {n_ov} of {n_co} sentences that cite only co-occurrence graph facts ({n_ov / n_co:.0%}) "
                      "nevertheless state a therapeutic role, which the facts do not support (automatic keyword check, so it is a lower bound)."]
    if "has_k" in answers.columns:
        L += ["", "Computed from the answers:", ""]
        for qt in sorted(answers["qtype"].unique()):
            f = answers[(answers["system"] == "full") & (answers["qtype"] == qt) & (answers["has_k"])]
            if len(f):
                L.append(f"- {qt}: the full system refused {int(f['refused'].sum())} of {len(f)} questions even though an answer-bearing KG fact was in its context "
                         "(a reliability limit of a small local model, not a retrieval failure).")
        for qt, note in (("top_drugs", "develop set: the K-first variant was designed after seeing failures here, so this is optimistic"),
                         ("top_herbs", "held-out: a question type not used when the K-first variant was designed")):
            a = answers[(answers["qtype"] == qt) & answers["system"].isin(["full", "full_kfirst"])].groupby("system")["correct"].mean()
            if {"full", "full_kfirst"} <= set(a.index):
                L.append(f"- {qt} ({note}): correctness with the original prompt order {a['full']:.3f} vs K-first {a['full_kfirst']:.3f}.")
    if overread is not None and len(overread):
        so = summarize_overread(overread).set_index("variant")
        L += ["", "## Over-reading of co-occurrence facts", "",
              "After the first run, reading the answers showed the model turning 'X is co-mentioned with Y' into 'X balances Y'. The graph-fact wording and the prompt rules "
              "were then revised (this was done **after** seeing those outputs, so it is a fix, not a blind test). The same herb-condition questions were answered with the old and "
              "the new wording/rules; a sentence counts as an over-reading when it cites only co-occurrence facts but states a therapeutic role (automatic keyword check, a lower bound).", ""]
        for v in ("before", "after"):
            if v in so.index and so.loc[v, "n_cocite"] > 0:
                r = so.loc[v]
                L.append(f"- {v} the fix: {int(r.n_overclaim)} of {int(r.n_cocite)} sentences that cite only co-occurrence facts state a therapeutic role "
                         f"({r.rate:.0%}) across {int(r.questions)} questions.")
            elif v in so.index:
                L.append(f"- {v} the fix: no sentences cited only co-occurrence facts ({int(so.loc[v, 'questions'])} questions).")
    L += ["", "Correctness: recall of the gold drugs/herbs (top-drugs and top-herbs questions) or whether the gold score appears within 0.03 (score questions). "
          "Citation validity: fraction of cited ids that exist in the retrieved context. Support rate: fraction of answer sentences whose content words appear "
          "in the cited sources (a lexical proxy, not an entailment judgement).", "", "## Qualitative examples", ""]
    for ex in examples:
        L += [f"**Q: {ex['question']}**", "", f"- plain RAG: {ex['plain']}", f"- GraphRAG (full): {ex['full']}", ""]
    L += ["## Limitations", "",
          "- **No expert-verified question set yet.** A CSV template (`data/processed/rag/expert_template.csv`) is ready; until an Ayurveda expert fills and verifies it, "
          "no claim about answer correctness on real questions is made.",
          "- Faithfulness and hallucination numbers are automatic proxies (citation validity, lexical support). They catch invented citations and unsupported sentences, not subtle errors.",
          "- **A known, undetected failure mode:** an irrelevant retrieved passage can be blended into an answer. In the ginger example the answer states that ginger is relevant "
          "to nausea and vomiting by citing a passage that is actually about *Randia dumetorum*. The lexical-support proxy scores this as fully supported, so only reading the "
          "answers (or an expert) catches it.",
          "- The prompt rules were revised after reading the first run's outputs (see the over-reading section); the K-first prompt variant was also designed after seeing failures. "
          "The question sets are small (12 / 20 / 35 / 60 questions) and the model is a single 8B local LLM, so differences of a few answers are within noise.",
          "- The texts are OCR output: some passages are noisy, there are no page numbers (citations use passage ids), and front-matter (testimonials) can be retrieved.",
          "- Triple extraction precision is unverified; object linking is by containment and can over-link (for example a phrase containing the word 'wind' links to the vata dosha).",
          "- Only two English translations are used; classical terminology varies, and the alias lexicon is a hand-written v1 for an advisor to review.",
          "- Generation uses a general-purpose open LLM (`qwen3:8b`). The AyurParam comparison from the plan is deferred (the project owner has not approved the download).",
          "- Interaction facts are research risk scores (mechanistic hypotheses with known false alarms), never advice."]
    return "\n".join(L) + "\n"


# ---------------- stages (need models; run via CLI) ----------------

def load_system():
    chunks = load_chunks()
    lex = load_lexicon()
    rows = load_triple_rows(OUT / "triples.jsonl")
    ents = {c["id"]: lex.entities(c["text"]) for c in chunks}
    graph = TextGraph.from_sources(cooccurrence_edges(ents, min_count=2), rows)
    graph.save(OUT / "text_graph.json")
    risk = pd.read_parquet("data/processed/phase5/herb_drug_risk.parquet")
    return {"chunks": chunks, "by_id": {c["id"]: c for c in chunks}, "lex": lex, "graph": graph, "rows": rows, "ents": ents, "risk": risk,
            "index": DenseIndex.load(OUT / "index.npz"), "embed": sentence_embedder(), "kg": KGFacts(risk)}


def retriever(sys_, cfg: str) -> HybridRetriever:
    return HybridRetriever(sys_["index"], sys_["embed"], sys_["by_id"], sys_["lex"], sys_["graph"], sys_["kg"], **CONFIGS[cfg])


def stats_of(sys_) -> dict:
    rows, chunks, lex = sys_["rows"], sys_["chunks"], sys_["lex"]
    per_text = {}
    for c in chunks:
        k = "Charaka" if c["id"].startswith("charaka") else "Sushruta"
        per_text[k] = per_text.get(k, 0) + 1
    rel = {}
    for r in rows:
        for a in r["accepted"]:
            rel[a["r"]] = rel.get(a["r"], 0) + 1
    herbs_found = {e for es in sys_["ents"].values() for e in es if e.startswith("herb:")}
    return {"n_chunks": len(chunks), "per_text": per_text, "herbs_found": len(herbs_found), "herbs_total": len(load_scope()["herbs"]),
            "cooccurrence_edges": sum(1 for e in sys_["graph"].edges if e["relation"] == "co-mentioned"), "triples_rows": len(rows),
            "triples_accepted": sum(len(r["accepted"]) for r in rows), "triples_rejected": sum(len(r["rejected"]) for r in rows),
            "triples_errors": sum(1 for r in rows if r["error"]), "relations": rel}


def retrieval_stage(sys_, n=60) -> pd.DataFrame:
    qpath = OUT / "retrieval_questions.json"
    if qpath.exists():
        qs = json.loads(qpath.read_text(encoding="utf-8"))
    else:
        cands = [c for c in sys_["chunks"] if any(e.startswith("herb:") for e in sys_["ents"][c["id"]]) and any(e.startswith("condition:") for e in sys_["ents"][c["id"]])]
        qs = ev.make_retrieval_questions(cands, ollama_client(num_predict=120), n=n, seed=0)
        qpath.write_text(json.dumps(qs, ensure_ascii=False), encoding="utf-8")
    rankers = {}
    for cfg in ("plain", "alias", "graph", "alias+graph"):
        r = retriever(sys_, cfg)
        rankers[cfg] = lambda q, r=r: [i["chunk"] for i in r.retrieve(q, k_passages=10) if i["kind"] == "P"]
    retr = ev.retrieval_eval(qs, rankers, ks=(5, 10))
    gq = ev.triple_questions(sys_["rows"], sys_["by_id"], load_scope(), n=60)          # English-name questions vs Sanskrit-name passages
    gap = ev.retrieval_eval(gq, rankers, ks=(5, 10)) if gq else None
    return retr, gap


def no_retrieval_answer(question: str, client) -> dict:
    try:
        text = client(f"Answer concisely (at most 120 words) using your own knowledge.\nQuestion: {question}\nAnswer:").strip()
        err = ""
    except Exception as e:
        text, err = "", f"{type(e).__name__}: {e}"
    return {"text": f"{text}\n\n{DISCLAIMER}", "model_text": text, "checks": check_citations(text, []), "support": {"rate": float("nan")}, "refused": False, "error": err}


def answer_stage(sys_) -> pd.DataFrame:
    path = OUT / "answers.jsonl"
    done = {(r["system"], r["qid"]) for r in map(json.loads, path.read_text(encoding="utf-8").splitlines())} if path.exists() else set()
    gold = curated.load_gold()
    pairs = list(dict.fromkeys(zip(gold["herb"], gold["drug"])))
    qs = ev.kg_questions(sys_["risk"], load_scope(), pairs, include_top_herbs=True)     # top_herbs = held-out type (drug -> herbs)
    client = ollama_text_client()
    with path.open("a", encoding="utf-8") as f:
        for q in qs:
            for system in ANSWER_SYSTEMS:
                if (system, q["id"]) in done:
                    continue
                has_k = False
                if system == "no_retrieval":
                    out, n_items = no_retrieval_answer(q["question"], client), 0
                else:
                    kfirst = system == "full_kfirst"
                    items = retriever(sys_, "full" if kfirst else system).retrieve(q["question"])
                    has_k = any(i["kind"] == "K" for i in items)
                    out, n_items = answer(q["question"], items, client, kind_order="KGP" if kfirst else None), len(items)
                if q["type"] in ("top_drugs", "top_herbs"):
                    correct = ev.score_top_drugs(out["model_text"], q["gold"])
                else:
                    correct = float(ev.score_pair_score(out["model_text"], q["gold"]))
                f.write(json.dumps({"system": system, "qid": q["id"], "qtype": q["type"], "correct": correct,
                                    "citation_validity": out["checks"]["citation_validity"], "support_rate": out["support"]["rate"],
                                    "refused": bool(out["refused"]), "n_items": n_items, "has_k": has_k,
                                    "n_cocite": out.get("overclaim", {}).get("n_cocite", 0), "n_overclaim": out.get("overclaim", {}).get("n_overclaim", 0),
                                    "answer": out["text"]}, ensure_ascii=False) + "\n")
                f.flush()
    return pd.DataFrame(map(json.loads, path.read_text(encoding="utf-8").splitlines()))


def examples_stage(sys_) -> list[dict]:
    client, out = ollama_text_client(), []
    for q in EXAMPLE_QUESTIONS:
        row = {"question": q}
        for name, cfg in (("plain", "plain"), ("full", "full")):
            row[name] = answer(q, retriever(sys_, cfg).retrieve(q), client)["text"].replace("\n", " ")
        out.append(row)
    return out


OLD_COMENTION_SUFFIX = " (co-occurrence only: this does not state that either affects the other)."


def overread_stage(sys_, n=30) -> pd.DataFrame:
    """Before/after comparison on herb-condition questions: OLD graph-fact wording + prompt without the two added rules vs the CURRENT ones."""
    path = OUT / "overread.jsonl"
    done = {(r["variant"], r["qid"]) for r in map(json.loads, path.read_text(encoding="utf-8").splitlines())} if path.exists() else set()
    qs = ev.triple_questions(sys_["rows"], sys_["by_id"], load_scope(), n=n)
    client = ollama_text_client()
    with path.open("a", encoding="utf-8") as f:
        for q in qs:
            for variant in ("before", "after"):
                if (variant, q["id"]) in done:
                    continue
                items = retriever(sys_, "full").retrieve(q["question"])
                if variant == "before":
                    items = [{**i, "text": i["text"].replace(OLD_COMENTION_SUFFIX, ".")} if i["kind"] == "G" else i for i in items]
                out = answer(q["question"], items, client, strict_rules=(variant == "after"))
                f.write(json.dumps({"variant": variant, "qid": q["id"], "n_cocite": out["overclaim"]["n_cocite"],
                                    "n_overclaim": out["overclaim"]["n_overclaim"], "refused": bool(out["refused"]), "answer": out["text"]}, ensure_ascii=False) + "\n")
                f.flush()
    df = pd.DataFrame(map(json.loads, path.read_text(encoding="utf-8").splitlines()))
    return recompute_overread(sys_, df, qs)


def recompute_overread(sys_, df: pd.DataFrame, qs: list[dict]) -> pd.DataFrame:
    """Recount over-readings from the STORED answers with the current detector (re-retrieves the same context; no new generation),
    so a detector fix never requires regenerating answers."""
    qmap, cache, co, ov = {q["id"]: q["question"] for q in qs}, {}, [], []
    for r in df.itertuples():
        if r.qid not in cache:
            cache[r.qid] = retriever(sys_, "full").retrieve(qmap[r.qid])
        items = cache[r.qid]
        if r.variant == "before":
            items = [{**i, "text": i["text"].replace(OLD_COMENTION_SUFFIX, ".")} if i["kind"] == "G" else i for i in items]
        flags = overclaim_flags(r.answer.replace(DISCLAIMER, ""), items)
        co.append(flags["n_cocite"])
        ov.append(flags["n_overclaim"])
    return df.assign(n_cocite=co, n_overclaim=ov)


def run_all(report_path="docs/phase6_results.md"):
    sys_ = load_system()
    retr, gap = retrieval_stage(sys_)
    answers = answer_stage(sys_)
    overread = overread_stage(sys_)
    ex_path = OUT / "examples.json"
    examples = json.loads(ex_path.read_text(encoding="utf-8")) if ex_path.exists() else examples_stage(sys_)
    ex_path.write_text(json.dumps(examples, ensure_ascii=False), encoding="utf-8")
    ev.write_expert_template(OUT / "expert_template.csv", [{"id": f"E{i + 1}", "question": q} for i, q in enumerate(EXAMPLE_QUESTIONS)])
    stats = stats_of(sys_)
    (OUT / "facts.json").write_text(json.dumps(phase6_facts(stats, retr, gap, answers, overread)), encoding="utf-8")
    Path(report_path).write_text(make_phase6_report(stats, retr, answers, examples, retr_gap=gap, overread=overread), encoding="utf-8")
    return retr, answers


if __name__ == "__main__":
    argparse.ArgumentParser().parse_args()
    retr, answers = run_all()
    print(retr.to_string(index=False))
    print(summarize_answers(answers).to_string(index=False))
