"""Phase 6 runner: text graph -> retrieval evaluation (synthetic questions) -> KG-grounded answer evaluation -> examples -> docs/phase6_results.md.
Stages are resumable and cached under data/processed/rag (derived from public-domain texts and local IMPPAT-derived data: not committed)."""
import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

from ayurveda_kg import curated
from ayurveda_kg.rag import evaluate as ev
from ayurveda_kg.rag.build_index import OUT, load_chunks
from ayurveda_kg.rag.extract import cooccurrence_edges, ollama_client
from ayurveda_kg.rag.generate import DISCLAIMER, answer, check_citations, ollama_text_client
from ayurveda_kg.rag.index import DenseIndex, sentence_embedder
from ayurveda_kg.rag.kgfacts import KGFacts
from ayurveda_kg.rag.lexicon import load_lexicon
from ayurveda_kg.rag.retrieve import HybridRetriever
from ayurveda_kg.rag.textgraph import TextGraph
from ayurveda_kg.scope import load_scope

CONFIGS = {"plain": dict(use_alias=False, use_graph=False, use_kg=False), "alias": dict(use_alias=True, use_graph=False, use_kg=False),
           "graph": dict(use_alias=False, use_graph=True, use_kg=False), "alias+graph": dict(use_alias=True, use_graph=True, use_kg=False),
           "full": dict(use_alias=True, use_graph=True, use_kg=True)}
ANSWER_SYSTEMS = ["no_retrieval", "plain", "alias+graph", "full"]
EXAMPLE_QUESTIONS = ["What does the Charaka Samhita say about treating cough?", "Which remedies are used for skin disease in the Sushruta Samhita?",
                     "How is turmeric used in classical Ayurveda?", "Is black pepper safe to take with phenytoin?",
                     "What is said about ginger and digestion?", "Which drugs may interact with licorice according to the research risk scores?"]


def summarize_answers(df: pd.DataFrame) -> pd.DataFrame:
    g = df.groupby(["system", "qtype"])
    return g.agg(correctness=("correct", "mean"), citation_validity=("citation_validity", "mean"), support_rate=("support_rate", "mean"),
                 refusal_rate=("refused", "mean"), n=("correct", "size")).reset_index()


def make_phase6_report(stats: dict, retr: pd.DataFrame, answers: pd.DataFrame, examples: list[dict]) -> str:
    L = ["# Phase 6 results", "", "Generated by `python -m ayurveda_kg.phase6`. Do not edit by hand.", "",
         "**What this is.** A GraphRAG assistant over two public-domain classical translations (Kaviratna *Charaka-Samhita*, Bhishagratna *Sushruta Samhita*) "
         "that retrieves passages, text-graph facts and project knowledge-graph facts (herb-drug research risk scores), answers with checkable citations using a "
         "local model (`qwen3:8b`), and always appends a research-use disclaimer. AyurParam is not used yet (deferred).", "",
         "## Corpus and graph", "",
         f"- {stats['n_chunks']} passages ({', '.join(f'{k}: {v}' for k, v in stats['per_text'].items())}).",
         f"- The alias lexicon finds {stats['herbs_found']} of {stats['herbs_total']} scoped herbs in the texts.",
         f"- Text graph: {stats['cooccurrence_edges']} co-occurrence edges (min 2 passages); LLM triple extraction over {stats['triples_rows']} herb+condition passages "
         f"accepted {stats['triples_accepted']} grounded triples and rejected {stats['triples_rejected']} ({stats['triples_errors']} model errors). "
         f"Relations: {', '.join(f'{k} {v}' for k, v in stats['relations'].items())}.",
         "- A triple is accepted only if its subject and object literally appear in the passage and resolve to lexicon entities. This removes hallucinated entities; "
         "the **precision of accepted triples is unverified until an expert checks a sample**.", "",
         "## Retrieval (synthetic questions)", "",
         "Questions were written by the local LLM from sampled passages (gold = the source passage). They are lexically easier than real questions, "
         "so absolute numbers are optimistic; the comparison between configurations is what matters.", "",
         "| config | recall@5 | recall@10 | MRR | questions |", "|---|---|---|---|---|"]
    L += [f"| {r.config} | {r._2:.3f} | {r._3:.3f} | {r.mrr:.3f} | {r.n} |" for r in retr.rename(columns={"recall@5": "_2", "recall@10": "_3"}).itertuples()]
    s = summarize_answers(answers)
    L += ["", "## KG-grounded multi-hop questions", "",
          "Questions are generated from the knowledge graph (top-3 highest-risk drugs for a herb; the risk score of a herb-drug pair) and scored programmatically. "
          "Systems that can see KG facts have an advantage **by construction**: this shows what the graph adds, not general answer quality.", "",
          "| system | question type | correctness | citation validity | support rate | refusal rate | n |", "|---|---|---|---|---|---|---|"]
    order = {s_: i for i, s_ in enumerate(ANSWER_SYSTEMS)}
    for r in s.sort_values(["qtype", "system"], key=lambda c: c.map(order) if c.name == "system" else c).itertuples():
        cv = "n/a" if pd.isna(r.citation_validity) else f"{r.citation_validity:.3f}"
        sr = "n/a" if pd.isna(r.support_rate) else f"{r.support_rate:.3f}"
        L.append(f"| {r.system} | {r.qtype} | {r.correctness:.3f} | {cv} | {sr} | {r.refusal_rate:.3f} | {r.n} |")
    L += ["", "Correctness: recall of the gold drugs (top-drugs questions) or whether the gold score appears within 0.03 (score questions). "
          "Citation validity: fraction of cited ids that exist in the retrieved context. Support rate: fraction of answer sentences whose content words appear "
          "in the cited sources (a lexical proxy, not an entailment judgement).", "", "## Qualitative examples", ""]
    for ex in examples:
        L += [f"**Q: {ex['question']}**", "", f"- plain RAG: {ex['plain']}", f"- GraphRAG (full): {ex['full']}", ""]
    L += ["## Limitations", "",
          "- **No expert-verified question set yet.** A CSV template (`data/processed/rag/expert_template.csv`) is ready; until an Ayurveda expert fills and verifies it, "
          "no claim about answer correctness on real questions is made.",
          "- Faithfulness and hallucination numbers are automatic proxies (citation validity, lexical support). They catch invented citations and unsupported sentences, not subtle errors.",
          "- The texts are OCR output: some passages are noisy, there are no page numbers (citations use passage ids), and front-matter (testimonials) can be retrieved.",
          "- Triple extraction precision is unverified; object linking is by containment and can over-link (for example a phrase containing the word 'wind' links to the vata dosha).",
          "- Only two English translations are used; classical terminology varies, and the alias lexicon is a hand-written v1 for an advisor to review.",
          "- Generation uses a general-purpose open LLM (`qwen3:8b`). The AyurParam comparison from the plan is deferred (the project owner has not approved the download).",
          "- Interaction facts are research risk scores (mechanistic hypotheses with known false alarms), never advice."]
    return "\n".join(L) + "\n"


# ---------------- stages (need models; run via CLI) ----------------

def load_system():
    chunks = load_chunks()
    lex = load_lexicon()
    rows = [json.loads(l) for l in (OUT / "triples.jsonl").read_text(encoding="utf-8").splitlines()] if (OUT / "triples.jsonl").exists() else []
    ents = {c["id"]: lex.entities(c["text"]) for c in chunks}
    graph = TextGraph.from_sources(cooccurrence_edges(ents, min_count=2), rows)
    graph.save(OUT / "text_graph.json")
    risk = pd.read_parquet("data/processed/phase5/herb_drug_risk.parquet")
    return {"chunks": chunks, "by_id": {c["id"]: c for c in chunks}, "lex": lex, "graph": graph, "rows": rows, "ents": ents, "risk": risk,
            "index": DenseIndex.load(OUT / "index.npz"), "embed": sentence_embedder(), "kg": KGFacts(risk)}


def retriever(sys_, cfg: str) -> HybridRetriever:
    return HybridRetriever(sys_["index"], sys_["embed"], sys_["by_id"], sys_["lex"], sys_["graph"], sys_["kg"], **CONFIGS[cfg])


def stats_of(sys_) -> dict:
    rows, chunks, lex = sys_["rows"], sys_["chunks"], sys_["lex"]
    per_text = {}
    for c in chunks:
        k = "Charaka" if c["id"].startswith("charaka") else "Sushruta"
        per_text[k] = per_text.get(k, 0) + 1
    rel = {}
    for r in rows:
        for a in r["accepted"]:
            rel[a["r"]] = rel.get(a["r"], 0) + 1
    herbs_found = {e for es in sys_["ents"].values() for e in es if e.startswith("herb:")}
    return {"n_chunks": len(chunks), "per_text": per_text, "herbs_found": len(herbs_found), "herbs_total": len(load_scope()["herbs"]),
            "cooccurrence_edges": sum(1 for e in sys_["graph"].edges if e["relation"] == "co-mentioned"), "triples_rows": len(rows),
            "triples_accepted": sum(len(r["accepted"]) for r in rows), "triples_rejected": sum(len(r["rejected"]) for r in rows),
            "triples_errors": sum(1 for r in rows if r["error"]), "relations": rel}


def retrieval_stage(sys_, n=60) -> pd.DataFrame:
    qpath = OUT / "retrieval_questions.json"
    if qpath.exists():
        qs = json.loads(qpath.read_text(encoding="utf-8"))
    else:
        cands = [c for c in sys_["chunks"] if any(e.startswith("herb:") for e in sys_["ents"][c["id"]]) and any(e.startswith("condition:") for e in sys_["ents"][c["id"]])]
        qs = ev.make_retrieval_questions(cands, ollama_client(num_predict=120), n=n, seed=0)
        qpath.write_text(json.dumps(qs, ensure_ascii=False), encoding="utf-8")
    rankers = {}
    for cfg in ("plain", "alias", "graph", "alias+graph"):
        r = retriever(sys_, cfg)
        rankers[cfg] = lambda q, r=r: [i["chunk"] for i in r.retrieve(q, k_passages=10) if i["kind"] == "P"]
    return ev.retrieval_eval(qs, rankers, ks=(5, 10))


def no_retrieval_answer(question: str, client) -> dict:
    try:
        text = client(f"Answer concisely (at most 120 words) using your own knowledge.\nQuestion: {question}\nAnswer:").strip()
        err = ""
    except Exception as e:
        text, err = "", f"{type(e).__name__}: {e}"
    return {"text": f"{text}\n\n{DISCLAIMER}", "model_text": text, "checks": check_citations(text, []), "support": {"rate": float("nan")}, "refused": False, "error": err}


def answer_stage(sys_) -> pd.DataFrame:
    path = OUT / "answers.jsonl"
    done = {(r["system"], r["qid"]) for r in map(json.loads, path.read_text(encoding="utf-8").splitlines())} if path.exists() else set()
    gold = curated.load_gold()
    pairs = list(dict.fromkeys(zip(gold["herb"], gold["drug"])))
    qs = ev.kg_questions(sys_["risk"], load_scope(), pairs)
    client = ollama_text_client()
    with path.open("a", encoding="utf-8") as f:
        for q in qs:
            for system in ANSWER_SYSTEMS:
                if (system, q["id"]) in done:
                    continue
                if system == "no_retrieval":
                    out, n_items = no_retrieval_answer(q["question"], client), 0
                else:
                    items = retriever(sys_, system).retrieve(q["question"])
                    out, n_items = answer(q["question"], items, client), len(items)
                correct = ev.score_top_drugs(out["model_text"], q["gold"]) if q["type"] == "top_drugs" else float(ev.score_pair_score(out["model_text"], q["gold"]))
                f.write(json.dumps({"system": system, "qid": q["id"], "qtype": q["type"], "correct": correct,
                                    "citation_validity": out["checks"]["citation_validity"], "support_rate": out["support"]["rate"],
                                    "refused": bool(out["refused"]), "n_items": n_items, "answer": out["text"]}, ensure_ascii=False) + "\n")
                f.flush()
    return pd.DataFrame(map(json.loads, path.read_text(encoding="utf-8").splitlines()))


def examples_stage(sys_) -> list[dict]:
    client, out = ollama_text_client(), []
    for q in EXAMPLE_QUESTIONS:
        row = {"question": q}
        for name, cfg in (("plain", "plain"), ("full", "full")):
            row[name] = answer(q, retriever(sys_, cfg).retrieve(q), client)["text"].replace("\n", " ")
        out.append(row)
    return out


def run_all(report_path="docs/phase6_results.md"):
    sys_ = load_system()
    retr = retrieval_stage(sys_)
    answers = answer_stage(sys_)
    ex_path = OUT / "examples.json"
    examples = json.loads(ex_path.read_text(encoding="utf-8")) if ex_path.exists() else examples_stage(sys_)
    ex_path.write_text(json.dumps(examples, ensure_ascii=False), encoding="utf-8")
    ev.write_expert_template(OUT / "expert_template.csv", [{"id": f"E{i + 1}", "question": q} for i, q in enumerate(EXAMPLE_QUESTIONS)])
    Path(report_path).write_text(make_phase6_report(stats_of(sys_), retr, answers, examples), encoding="utf-8")
    return retr, answers


if __name__ == "__main__":
    argparse.ArgumentParser().parse_args()
    retr, answers = run_all()
    print(retr.to_string(index=False))
    print(summarize_answers(answers).to_string(index=False))
