"""Phase 3 run: silver labels -> aggregates -> leak-safe split statistics -> gold comparison -> docs/labels_report.md.
Aggregate numbers only; the compound-level label table stays local (IMPPAT-derived, not redistributed)."""
from pathlib import Path

import pandas as pd

from ayurveda_kg import curated
from ayurveda_kg.kg import load_tables
from ayurveda_kg.labels import gold_vs_silver, herb_drug_scores, silver_labels
from ayurveda_kg.masking import assert_no_label_leak, mask_label_edges
from ayurveda_kg.scope import load_scope
from ayurveda_kg.splits import assert_disjoint, herb_group_folds, split_pairs


def make_labels_report(labels, drug_names, splits, gold_cmp) -> str:
    c = labels["label"].value_counts()
    L = ["# Phase 3 labels report", "", "Generated by `python -m ayurveda_kg.phase3`. Aggregate numbers only; do not edit by hand.", "",
         "## Silver labels (compound-drug, mechanistic)", "", "| Label | Pairs |", "|---|---|",
         f"| positive (1) | {c.get(1, 0)} |", f"| negative (0) | {c.get(0, 0)} |", f"| unlabelled (-1) | {c.get(-1, 0)} |", "",
         "## Per drug", "", "| Drug | Positive | Negative | Unlabelled |", "|---|---|---|---|"]
    g = labels.groupby("drug")["label"].agg(pos=lambda x: (x == 1).sum(), neg=lambda x: (x == 0).sum(), unl=lambda x: (x == -1).sum())
    L += [f"| {drug_names.get(d, d)} | {r.pos} | {r.neg} | {r.unl} |" for d, r in g.sort_values("pos", ascending=False).iterrows()]
    L += ["", "## Cold-herb folds (each herb held out once; compounds shared with training herbs are dropped, not guessed)", "",
          "| fold | test_herbs | train_compounds | test_compounds | shared_dropped | train_pairs | test_pairs | test_pos |", "|---|---|---|---|---|---|---|---|"]
    L += [f"| {s['fold']} | {s['test_herbs']} | {s['train_compounds']} | {s['test_compounds']} | {s['shared_dropped']} | "
          f"{s['train_pairs']} | {s['test_pairs']} | {s['test_pos']} |" for s in splits]
    L += ["", "## Silver labels vs the literature gold set", "",
          "Silver score = fraction of the herb's labelled compounds positive for the drug; percentile = rank among all scored herb-drug pairs.", "",
          "| Herb | Drug | Gold | Mechanism | Evidence | Silver score | Percentile |", "|---|---|---|---|---|---|---|"]
    L += [f"| {r.herb} | {r.drug} | {r.label} | {r.mechanism} | {r.evidence} | {r.frac_pos:.2f} | {r.percentile:.2f} |"
          if pd.notna(r.frac_pos) else f"| {r.herb} | {r.drug} | {r.label} | {r.mechanism} | {r.evidence} | n/a | n/a |" for r in gold_cmp.itertuples()]
    L += ["", "**Reading this table:** silver labels are a *mechanistic hypothesis* (predicted CYP inhibition meets known substrate), not a clinical "
          "interaction. A negative gold pair with a high silver percentile is a silver false alarm; a pharmacodynamic gold pair (mechanism PD) is "
          "expected to score low because the silver rule only models CYP pharmacokinetics. The gold set is small and pending expert review, so it "
          "supports a qualitative case study, not statistical claims."]
    return "\n".join(L) + "\n"


def run(kg_dir="data/processed/kg", out_dir="data/processed/labels", report_path="docs/labels_report.md", k=5, seed=0):
    nodes, edges = load_tables(kg_dir)
    labels = silver_labels(nodes, edges)
    assert_no_label_leak(mask_label_edges(edges))                       # fail loudly before anything is saved
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    labels.to_parquet(Path(out_dir) / "silver.parquet", index=False)
    splits = []
    for f, (test_herbs, train, test, shared) in enumerate(herb_group_folds(edges["contains"], k=k, seed=seed)):
        assert_disjoint(train, test)
        tr, te = split_pairs(labels, train, test)
        splits.append({"fold": f, "test_herbs": len(test_herbs), "train_compounds": len(train), "test_compounds": len(test),
                       "shared_dropped": len(shared), "train_pairs": len(tr), "test_pairs": len(te), "test_pos": int((te["label"] == 1).sum())})
    scores = herb_drug_scores(labels, edges["contains"])
    cmp_ = gold_vs_silver(curated.load_gold(), scores)
    names = dict(zip(nodes["Drug"]["id"], nodes["Drug"]["name"]))
    Path(report_path).write_text(make_labels_report(labels, names, splits, cmp_), encoding="utf-8")
    return labels, splits, cmp_


if __name__ == "__main__":
    assert curated.validate_gold(curated.load_gold(), load_scope()) == []
    labels, splits, cmp_ = run()
    print(labels["label"].value_counts().to_dict())
    print(pd.DataFrame(splits).to_string(index=False))
