"""Human-readable coverage report for the KG (written to docs/kg_report.md by the pipeline)."""


def _names_without(nodes_df, edges_df, col):
    have = set(edges_df[col]) if edges_df is not None and len(edges_df) else set()
    return [n for i, n in zip(nodes_df["id"], nodes_df["name"]) if i not in have]


def make_report(nodes, edges, meta) -> str:
    L = ["# KG build report", "", "Generated by `python -m ayurveda_kg.build`. Do not edit by hand.", "",
         f"Compounds crawled: {meta['compounds_crawled']} of {meta['compounds_expected']} expected "
         f"(a partial crawl means the herb-compound coverage below is incomplete).", "",
         "## Node counts", "", "| Type | Count |", "|---|---|"]
    L += [f"| {t} | {len(df)} |" for t, df in nodes.items()]
    L += ["", "## Edge counts", "", "| Type | Count |", "|---|---|"]
    L += [f"| {t} | {len(df)} |" for t, df in edges.items()]
    herbs = _names_without(nodes["Herb"], edges.get("contains"), "src")
    L += ["", "## Coverage gaps", "", f"- Herbs with no crawled compounds: {', '.join(herbs) or 'none'}"]
    for et in ("substrate_of", "targets"):
        L.append(f"- Drugs with no {et} edge: {', '.join(_names_without(nodes['Drug'], edges.get(et), 'src')) or 'none'}")
    L += ["", "## Validation", ""]
    L += [f"- {p}" for p in meta["problems"]] if meta["problems"] else ["No validation problems."]
    return "\n".join(L) + "\n"
